export const POST_CREATED = 'POST_CREATED'
export const POST_UPDATED = 'POST_UPDATED'
export const POST_DELETED = 'POST_DELETED'
export const POST_UPVOTE = 'POST_UPVOTE'
export const POST_DOWNVOTE = 'POST_DOWNVOTE'

export const USER_CREATED = 'USER_CREATED'
export const USER_UPDATED = 'USER_UPDATED'
export const USER_DELETED = 'USER_DELETED'

export const COMMENT_CREATED = 'COMMENT_CREATED'
export const COMMENT_UPDATED = 'COMMENT_UPDATED'
export const COMMENT_DELETED = 'COMMENT_DELETED'
export const COMMENT_UPVOTE = 'COMMENT_UPVOTE'
export const COMMENT_DOWNVOTE = 'COMMENT_DOWNVOTE'

export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const AUTH_USER = 'AUTH_USER'
