version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-35-174-127-63.compute-1.amazonaws.com
            port: 5432
            rawAccess: true
            database: d5mop5r2jncck6
            user: potetlrhevaict
            password: bb242d1ba844a6c99d3460018fc1563a8e094ffbced40bbfa195714e8bb289c0
            ssl: true
