version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-52-86-33-50.compute-1.amazonaws.com
            database: dbv0fg3h7dcsr8
            user: jhbrykkttudiii
            password: 3654dd10ea69433ddac5655a744c7bdc0fe231d2b3e9427db0cf6fdb19eb3148
            ssl: true
            rawAccess: true
            port: 5432
            migrations: true
