version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-18-214-119-135.compute-1.amazonaws.com
            database: d3dbq1i5hq9k5o
            schema: public
            user: eujfohqosgbugt
            password: 5ed41e38ee2351f2b6a3adb44df477638321b209eeb360286023342548158ab5
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true