version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${env:PRISMA_DB_HOST}
            database: ${env:PRISMA_DB_NAME}
            user: ${env:PRISMA_DB_USER}
            password: ${env:PRISMA_DB_PASS}
            ssl: true
            rawAccess: true
            port: 5432
            migrations: true
